steps:
  # - id: "Criando build da imagem"
  #   name: "gcr.io/cloud-builders/docker"
  #   args: ["docker", "build", "-t", "$PROJECT_ID/golangsum", "Dockerfile"]

  - id: "Buildando imagem"
    name: "gcr.io/cloud-builders/docker"
    args:
      # ["docker", "build", "-t", "gcr.io/$PROJECT_ID/golangsum:latest", "."]
      - "build"
      # - "--build-arg"
      # - "DOCKER_COMPOSE_VERSION=${_DOCKER_COMPOSE_VERSION}"
      - "-t"
      - "gcr.io/$PROJECT_ID/golangsum:latest" 
      - "."

  - id: "Listando imagens"
    name: "gcr.io/cloud-builders/docker"
    args: [image", "ls"]

  - id: "Iniciando container"
    name: "gcr.io/cloud-builders/docker"
    args: 
    # ["docker", "run", "-t", "gcr.io/$PROJECT_ID/golangsum", "Dockerfile"]
    - "run"     
    - "--name"
    - "app"
    - "gcr.io/$PROJECT_ID/golangsum"
    

  - id: "Executando testes unitários"
    name: "gcr.io/cloud-builders/docker"
    args:
      ["docker", "exec", "app", "cd go/src && go test"]
