steps:

  - id: "Buildando imagem"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/golangsum:latest" 
      - "."

  - id: "Listando imagens"
    name: "gcr.io/cloud-builders/docker"
    args: ["image", "ls"]

  - id: "Iniciando container"
    name: "gcr.io/cloud-builders/docker"
    args: 
    - "run"
    - -d     
    - -it
    - "--name"
    - "app"
    - "gcr.io/$PROJECT_ID/golangsum"
    

  - id: "Executando testes unitários"
    name: "gcr.io/cloud-builders/docker"
    args:
      ["exec", "app", "go","test"]
